openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
  description: API for managing user authentication, status, registration and retrieval.
servers:
  - url: http://localhost:3000  # Замени на URL твоего API, например, https://yourdomain.com

paths:
  /users/authentication/{username}/{password}:
    post:
      summary: Authenticate user
      description: Authenticates a user given a username and password.
      parameters:
        - in: path
          name: username
          required: true
          schema:
            type: string
          description: The username of the user to authenticate.
        - in: path
          name: password
          required: true
          schema:
            type: string
          description: The password of the user to authenticate.
      responses:
        200:
          description: User authenticated successfully. Returns the user username.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User logged in successfully
                  username:
                    type: string
                    example: "123"
        404:
          description: Invalid username or password.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Wrong username or password
                  username:
                    type: string
                    example: testuser
                  password:
                    type: string
                    example: testpassword
        500:
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Error
                  error:
                    type: string
                    example: Database connection error

  /users/status/{username}/{password}:
    get:
      summary: Get user status
      description: Checks the login status of a user, given a username and password.
      parameters:
        - in: path
          name: username
          required: true
          schema:
            type: string
          description: The username of the user to check.
        - in: path
          name: password
          required: true
          schema:
            type: string
          description: The password of the user to check.
      responses:
        200:
          description: User status retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User status checked successfully
                  logged:
                    type: boolean
                    example: true
        404:
          description: Invalid username or password.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Wrong username or password
                  username:
                    type: string
                    example: testuser
                  password:
                    type: string
                    example: testpassword
        500:
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Error
                  error:
                    type: string
                    example: Database connection error

  /users:
    get:
      summary: Get all users
      description: Retrieves a list of all users in the system.
      responses:
        200:
          description: List of users retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Users get successfully
                  users:
                    type: array
                    items:
                      type: object
                      id:
                       type: integer
                       description: The user ID


        500:
          description: Internal server error.